# Generated by Django 5.0.3 on 2024-04-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='signature',
            field=models.CharField(default='Demayne Govender', max_length=140),
        ),
    ]
